-- Logs begin at Mon 2022-07-18 19:58:37 IST, end at Mon 2022-07-18 19:59:51 IST. --
Jul 18 19:58:37 datacore-PowerEdge-R740 sudo[305583]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:37 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 0.857s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:37 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:37 datacore-PowerEdge-R740 sudo[305698]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 18 19:58:37 datacore-PowerEdge-R740 sudo[305698]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:38 datacore-PowerEdge-R740 sudo[305698]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:38 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.677s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:38 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:38 datacore-PowerEdge-R740 sudo[305745]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 18 19:58:38 datacore-PowerEdge-R740 sudo[305745]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:39 datacore-PowerEdge-R740 sudo[305745]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:39 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.660s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:39 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:39 datacore-PowerEdge-R740 sudo[305757]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 18 19:58:39 datacore-PowerEdge-R740 sudo[305757]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:39 datacore-PowerEdge-R740 sudo[305757]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:39 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.677s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:39 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:39 datacore-PowerEdge-R740 sudo[305778]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 18 19:58:39 datacore-PowerEdge-R740 sudo[305778]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:40 datacore-PowerEdge-R740 sudo[305778]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:40 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.653s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:40 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:40 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.018s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:40 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:40 datacore-PowerEdge-R740 sudo[305783]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 18 19:58:40 datacore-PowerEdge-R740 sudo[305783]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:41 datacore-PowerEdge-R740 sudo[305783]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:41 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.655s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:41 datacore-PowerEdge-R740 cinder-volume[305451]: INFO cinder.volume.drivers.lvm [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Enabling LVM thin provisioning by default because a thin pool exists.
Jul 18 19:58:41 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:41 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.021s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:41 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:41 datacore-PowerEdge-R740 sudo[305799]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 18 19:58:41 datacore-PowerEdge-R740 sudo[305799]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:41 datacore-PowerEdge-R740 sudo[305799]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:41 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.633s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:41 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG cinder.volume.drivers.lvm [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Updating volume stats {{(pid=305451) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Jul 18 19:58:41 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:41 datacore-PowerEdge-R740 sudo[305805]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 18 19:58:41 datacore-PowerEdge-R740 sudo[305805]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:42 datacore-PowerEdge-R740 sudo[305805]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:42 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.647s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:42 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:42 datacore-PowerEdge-R740 sudo[305815]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 18 19:58:42 datacore-PowerEdge-R740 sudo[305815]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:43 datacore-PowerEdge-R740 sudo[305815]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:43 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.698s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:43 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:43 datacore-PowerEdge-R740 sudo[305825]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 18 19:58:43 datacore-PowerEdge-R740 sudo[305825]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:43 datacore-PowerEdge-R740 cinder-volume[305241]: DEBUG dbcounter [-] [305241] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=305241) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Jul 18 19:58:43 datacore-PowerEdge-R740 sudo[305825]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:43 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.645s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:43 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:43 datacore-PowerEdge-R740 sudo[305830]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 18 19:58:43 datacore-PowerEdge-R740 sudo[305830]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:44 datacore-PowerEdge-R740 sudo[305830]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:44 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.637s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:44 datacore-PowerEdge-R740 cinder-volume[305451]: INFO cinder.volume.driver [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Driver hasn't implemented _init_vendor_properties()
Jul 18 19:58:44 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG cinder.volume.driver [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=305451) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:811}}
Jul 18 19:58:44 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_db.sqlalchemy.engines [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=305451) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 18 19:58:44 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG dbcounter [-] [305451] Writer thread running {{(pid=305451) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 18 19:58:44 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG cinder.db.sqlalchemy.api [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Building query based on filter {{(pid=305451) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3378}}
Jul 18 19:58:44 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG cinder.image.image_utils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=305451) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:955}}
Jul 18 19:58:44 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG cinder.volume.drivers.lvm [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Updating volume stats {{(pid=305451) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Jul 18 19:58:44 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:44 datacore-PowerEdge-R740 cinder-volume[305451]: INFO cinder.keymgr.migration [None req-2f5a30cb-31ff-43c2-b6fe-ce2f212de70d None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Jul 18 19:58:44 datacore-PowerEdge-R740 sudo[305842]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 18 19:58:44 datacore-PowerEdge-R740 sudo[305842]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:45 datacore-PowerEdge-R740 sudo[305842]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:45 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.657s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:45 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:45 datacore-PowerEdge-R740 sudo[305867]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 18 19:58:45 datacore-PowerEdge-R740 sudo[305867]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:45 datacore-PowerEdge-R740 sudo[305867]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:45 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.651s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:45 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:45 datacore-PowerEdge-R740 sudo[305872]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 18 19:58:45 datacore-PowerEdge-R740 sudo[305872]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:46 datacore-PowerEdge-R740 sudo[305872]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:46 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.647s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:46 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:46 datacore-PowerEdge-R740 sudo[305884]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 18 19:58:46 datacore-PowerEdge-R740 sudo[305884]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:47 datacore-PowerEdge-R740 sudo[305884]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.651s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG cinder.manager [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Notifying Schedulers of capabilities ... {{(pid=305451) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: INFO cinder.volume.manager [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Driver initialization completed successfully.
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: INFO cinder.manager [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Initiating service 2 cleanup
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: INFO cinder.manager [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Service 2 cleanup completed.
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG cinder.service [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Creating RPC server for service cinder-volume {{(pid=305451) start /opt/stack/cinder/cinder/service.py:231}}
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG cinder.service [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=305451) start /opt/stack/cinder/cinder/service.py:237}}
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: INFO cinder.volume.manager [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG cinder.volume.drivers.lvm [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Updating volume stats {{(pid=305451) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:47 datacore-PowerEdge-R740 sudo[305894]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 18 19:58:47 datacore-PowerEdge-R740 sudo[305894]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:47 datacore-PowerEdge-R740 sudo[305894]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.645s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:47 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:47 datacore-PowerEdge-R740 sudo[305916]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 18 19:58:47 datacore-PowerEdge-R740 sudo[305916]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:48 datacore-PowerEdge-R740 sudo[305916]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:48 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.669s {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 18 19:58:48 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.processutils [None req-c054da6a-3433-4cdb-bf36-69f573914905 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=305451) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 18 19:58:48 datacore-PowerEdge-R740 sudo[305936]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 18 19:58:48 datacore-PowerEdge-R740 sudo[305936]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 18 19:58:49 datacore-PowerEdge-R740 systemd[1]: Stopping Devstack devstack@c-vol.service...
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: INFO oslo_service.service [None req-72b5c9f3-8b35-43d0-9cfb-e7f3b69385a5 None None] Caught SIGTERM, stopping children
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: DEBUG oslo_concurrency.lockutils [None req-72b5c9f3-8b35-43d0-9cfb-e7f3b69385a5 None None] Acquired lock "singleton_lock" {{(pid=305241) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: DEBUG oslo_concurrency.lockutils [None req-72b5c9f3-8b35-43d0-9cfb-e7f3b69385a5 None None] Releasing lock "singleton_lock" {{(pid=305241) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: DEBUG oslo_service.service [None req-72b5c9f3-8b35-43d0-9cfb-e7f3b69385a5 None None] Stop services. {{(pid=305241) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:695}}
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: DEBUG oslo_service.service [None req-72b5c9f3-8b35-43d0-9cfb-e7f3b69385a5 None None] Killing children. {{(pid=305241) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:700}}
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: INFO oslo_service.service [None req-72b5c9f3-8b35-43d0-9cfb-e7f3b69385a5 None None] Waiting on 1 children to exit
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.lockutils [None req-72b5c9f3-8b35-43d0-9cfb-e7f3b69385a5 None None] Acquired lock "singleton_lock" {{(pid=305451) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305451]: DEBUG oslo_concurrency.lockutils [None req-72b5c9f3-8b35-43d0-9cfb-e7f3b69385a5 None None] Releasing lock "singleton_lock" {{(pid=305451) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305451]: WARNING amqp [None req-72b5c9f3-8b35-43d0-9cfb-e7f3b69385a5 None None] Received method (60, 30) during closing channel 1. This method will be ignored
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305451]: WARNING amqp [None req-72b5c9f3-8b35-43d0-9cfb-e7f3b69385a5 None None] Received method (60, 30) during closing channel 1. This method will be ignored
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: INFO oslo_service.service [None req-72b5c9f3-8b35-43d0-9cfb-e7f3b69385a5 None None] Child 305451 exited with status 0
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]:   from cryptography.utils import int_from_bytes
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]:   from cryptography.utils import int_from_bytes
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]:   last_heartbeat = column_property(
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]:   num_hosts = column_property(
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 18 19:58:49 datacore-PowerEdge-R740 cinder-volume[305241]:   num_down_hosts = column_property(
Jul 18 19:58:49 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Succeeded.
Jul 18 19:58:49 datacore-PowerEdge-R740 systemd[1]: Stopped Devstack devstack@c-vol.service.
Jul 18 19:58:49 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Found left-over process 305936 (sudo) in control group while starting unit. Ignoring.
Jul 18 19:58:49 datacore-PowerEdge-R740 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jul 18 19:58:49 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Found left-over process 305937 (cinder-rootwrap) in control group while starting unit. Ignoring.
Jul 18 19:58:49 datacore-PowerEdge-R740 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jul 18 19:58:49 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 18 19:58:49 datacore-PowerEdge-R740 sudo[305936]: pam_unix(sudo:session): session closed for user root
Jul 18 19:58:51 datacore-PowerEdge-R740 cinder-volume[305966]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=305966) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 18 19:58:51 datacore-PowerEdge-R740 cinder-volume[305966]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=305966) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 18 19:58:51 datacore-PowerEdge-R740 cinder-volume[305966]: INFO dbcounter [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] Registered counter for database cinder
Jul 18 19:58:51 datacore-PowerEdge-R740 cinder-volume[305966]: DEBUG oslo_db.sqlalchemy.engines [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=305966) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 18 19:58:51 datacore-PowerEdge-R740 cinder-volume[305966]: DEBUG dbcounter [-] [305966] Writer thread running {{(pid=305966) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 18 19:58:51 datacore-PowerEdge-R740 cinder-volume[305966]: INFO cinder.rpc [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 18 19:58:51 datacore-PowerEdge-R740 cinder-volume[305966]: INFO cinder.rpc [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 18 19:58:51 datacore-PowerEdge-R740 cinder-volume[305966]: DEBUG oslo_db.sqlalchemy.engines [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=305966) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: INFO cinder.volume.manager [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] Determined volume DB was empty at startup.
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: DEBUG cinder.volume.manager [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] Cinder Volume DB check: vol_db_empty=True {{(pid=305966) __init__ /opt/stack/cinder/cinder/volume/manager.py:286}}
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: INFO cinder.volume.manager [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] Service not found for updating active_backend_id, assuming default for driver init.
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: WARNING stevedore.named [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: WARNING castellan.key_manager [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: WARNING cinder.keymgr.conf_key_mgr [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 309, in __init__
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume 
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: ERROR cinder.cmd.volume [None req-7d0dcfea-db27-42ab-9ebd-720b94b4892b None None] No volume service(s) started successfully, terminating.
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]:   from cryptography.utils import int_from_bytes
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]:   from cryptography.utils import int_from_bytes
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]:   last_heartbeat = column_property(
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]:   num_hosts = column_property(
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 18 19:58:52 datacore-PowerEdge-R740 cinder-volume[305966]:   num_down_hosts = column_property(
Jul 18 19:58:52 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 18 19:58:52 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
