-- Logs begin at Wed 2022-07-06 20:09:02 IST, end at Wed 2022-07-06 20:13:54 IST. --
Jul 06 20:09:13 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2058696) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2058696) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: INFO dbcounter [None req-faeb076f-35ab-420b-900a-73f299617183 None None] Registered counter for database cinder
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: DEBUG oslo_db.sqlalchemy.engines [None req-faeb076f-35ab-420b-900a-73f299617183 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2058696) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: DEBUG dbcounter [-] [2058696] Writer thread running {{(pid=2058696) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: INFO cinder.rpc [None req-faeb076f-35ab-420b-900a-73f299617183 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: INFO cinder.rpc [None req-faeb076f-35ab-420b-900a-73f299617183 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: DEBUG oslo_db.sqlalchemy.engines [None req-faeb076f-35ab-420b-900a-73f299617183 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2058696) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: INFO cinder.volume.manager [None req-faeb076f-35ab-420b-900a-73f299617183 None None] Determined volume DB was empty at startup.
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: DEBUG cinder.volume.manager [None req-faeb076f-35ab-420b-900a-73f299617183 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2058696) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: WARNING stevedore.named [None req-faeb076f-35ab-420b-900a-73f299617183 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: WARNING castellan.key_manager [None req-faeb076f-35ab-420b-900a-73f299617183 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: WARNING cinder.keymgr.conf_key_mgr [None req-faeb076f-35ab-420b-900a-73f299617183 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume [None req-faeb076f-35ab-420b-900a-73f299617183 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume 
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: ERROR cinder.cmd.volume [None req-faeb076f-35ab-420b-900a-73f299617183 None None] No volume service(s) started successfully, terminating.
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]:   from cryptography.utils import int_from_bytes
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]:   from cryptography.utils import int_from_bytes
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]:   last_heartbeat = column_property(
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]:   num_hosts = column_property(
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 06 20:09:15 datacore-PowerEdge-R740 cinder-volume[2058696]:   num_down_hosts = column_property(
Jul 06 20:09:16 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 20:09:16 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jul 06 20:12:33 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 06 20:12:35 datacore-PowerEdge-R740 cinder-volume[2060185]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2060185) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 06 20:12:35 datacore-PowerEdge-R740 cinder-volume[2060185]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2060185) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 06 20:12:35 datacore-PowerEdge-R740 cinder-volume[2060185]: INFO dbcounter [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] Registered counter for database cinder
Jul 06 20:12:35 datacore-PowerEdge-R740 cinder-volume[2060185]: DEBUG oslo_db.sqlalchemy.engines [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2060185) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 06 20:12:35 datacore-PowerEdge-R740 cinder-volume[2060185]: DEBUG dbcounter [-] [2060185] Writer thread running {{(pid=2060185) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: INFO cinder.rpc [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: INFO cinder.rpc [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: DEBUG oslo_db.sqlalchemy.engines [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2060185) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: INFO cinder.volume.manager [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] Determined volume DB was empty at startup.
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: DEBUG cinder.volume.manager [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2060185) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: WARNING stevedore.named [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: WARNING castellan.key_manager [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: WARNING cinder.keymgr.conf_key_mgr [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume 
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: ERROR cinder.cmd.volume [None req-f02f3bd2-b374-45c5-87de-8bd69bb46a7d None None] No volume service(s) started successfully, terminating.
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]:   from cryptography.utils import int_from_bytes
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]:   from cryptography.utils import int_from_bytes
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]:   last_heartbeat = column_property(
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]:   num_hosts = column_property(
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 06 20:12:36 datacore-PowerEdge-R740 cinder-volume[2060185]:   num_down_hosts = column_property(
Jul 06 20:12:36 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 20:12:36 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jul 06 20:12:52 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 06 20:12:54 datacore-PowerEdge-R740 cinder-volume[2060801]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2060801) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 06 20:12:54 datacore-PowerEdge-R740 cinder-volume[2060801]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2060801) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 06 20:12:54 datacore-PowerEdge-R740 cinder-volume[2060801]: INFO dbcounter [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] Registered counter for database cinder
Jul 06 20:12:54 datacore-PowerEdge-R740 cinder-volume[2060801]: DEBUG oslo_db.sqlalchemy.engines [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2060801) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 06 20:12:54 datacore-PowerEdge-R740 cinder-volume[2060801]: DEBUG dbcounter [-] [2060801] Writer thread running {{(pid=2060801) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: INFO cinder.rpc [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: INFO cinder.rpc [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: DEBUG oslo_db.sqlalchemy.engines [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2060801) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: INFO cinder.volume.manager [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] Determined volume DB was empty at startup.
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: DEBUG cinder.volume.manager [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2060801) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: WARNING stevedore.named [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: WARNING castellan.key_manager [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: WARNING cinder.keymgr.conf_key_mgr [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume 
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: ERROR cinder.cmd.volume [None req-ed64d758-3f68-4ba5-9254-43d66d140e01 None None] No volume service(s) started successfully, terminating.
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]:   from cryptography.utils import int_from_bytes
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]:   from cryptography.utils import int_from_bytes
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]:   last_heartbeat = column_property(
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]:   num_hosts = column_property(
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 06 20:12:55 datacore-PowerEdge-R740 cinder-volume[2060801]:   num_down_hosts = column_property(
Jul 06 20:12:55 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 20:12:55 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
