-- Logs begin at Tue 2022-07-05 07:49:42 IST, end at Tue 2022-07-05 12:37:50 IST. --
Jul 05 12:36:29 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 05 12:36:31 datacore-PowerEdge-R740 cinder-volume[1759426]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1759426) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 05 12:36:31 datacore-PowerEdge-R740 cinder-volume[1759426]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1759426) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 05 12:36:31 datacore-PowerEdge-R740 cinder-volume[1759426]: INFO dbcounter [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] Registered counter for database cinder
Jul 05 12:36:31 datacore-PowerEdge-R740 cinder-volume[1759426]: DEBUG oslo_db.sqlalchemy.engines [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1759426) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 05 12:36:31 datacore-PowerEdge-R740 cinder-volume[1759426]: DEBUG dbcounter [-] [1759426] Writer thread running {{(pid=1759426) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: INFO cinder.rpc [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: INFO cinder.rpc [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: DEBUG oslo_db.sqlalchemy.engines [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1759426) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: INFO cinder.volume.manager [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] Determined volume DB was empty at startup.
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: DEBUG cinder.volume.manager [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=1759426) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: WARNING stevedore.named [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: WARNING castellan.key_manager [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: WARNING cinder.keymgr.conf_key_mgr [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume 
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: ERROR cinder.cmd.volume [None req-23a4146f-a115-413f-b93c-f42adfc907c2 None None] No volume service(s) started successfully, terminating.
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]:   from cryptography.utils import int_from_bytes
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]:   from cryptography.utils import int_from_bytes
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]:   last_heartbeat = column_property(
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]:   num_hosts = column_property(
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 05 12:36:32 datacore-PowerEdge-R740 cinder-volume[1759426]:   num_down_hosts = column_property(
Jul 05 12:36:32 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 05 12:36:32 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jul 05 12:36:48 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 05 12:36:50 datacore-PowerEdge-R740 cinder-volume[1760030]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1760030) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 05 12:36:50 datacore-PowerEdge-R740 cinder-volume[1760030]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1760030) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 05 12:36:50 datacore-PowerEdge-R740 cinder-volume[1760030]: INFO dbcounter [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] Registered counter for database cinder
Jul 05 12:36:50 datacore-PowerEdge-R740 cinder-volume[1760030]: DEBUG oslo_db.sqlalchemy.engines [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1760030) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 05 12:36:50 datacore-PowerEdge-R740 cinder-volume[1760030]: DEBUG dbcounter [-] [1760030] Writer thread running {{(pid=1760030) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 05 12:36:50 datacore-PowerEdge-R740 cinder-volume[1760030]: INFO cinder.rpc [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 05 12:36:50 datacore-PowerEdge-R740 cinder-volume[1760030]: INFO cinder.rpc [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 05 12:36:50 datacore-PowerEdge-R740 cinder-volume[1760030]: DEBUG oslo_db.sqlalchemy.engines [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1760030) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: INFO cinder.volume.manager [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] Determined volume DB was empty at startup.
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: DEBUG cinder.volume.manager [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=1760030) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: WARNING stevedore.named [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: WARNING castellan.key_manager [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: WARNING cinder.keymgr.conf_key_mgr [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume 
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: ERROR cinder.cmd.volume [None req-8c538133-1cad-4174-8b44-b31f5ab52c20 None None] No volume service(s) started successfully, terminating.
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]:   from cryptography.utils import int_from_bytes
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]:   from cryptography.utils import int_from_bytes
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]:   last_heartbeat = column_property(
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]:   num_hosts = column_property(
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 05 12:36:51 datacore-PowerEdge-R740 cinder-volume[1760030]:   num_down_hosts = column_property(
Jul 05 12:36:51 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 05 12:36:51 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
