-- Logs begin at Mon 2022-07-04 14:58:56 IST, end at Mon 2022-07-04 17:19:05 IST. --
Jul 04 17:17:44 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1579674) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1579674) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: INFO dbcounter [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] Registered counter for database cinder
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: DEBUG oslo_db.sqlalchemy.engines [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1579674) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: DEBUG dbcounter [-] [1579674] Writer thread running {{(pid=1579674) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: INFO cinder.rpc [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: INFO cinder.rpc [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: DEBUG oslo_db.sqlalchemy.engines [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1579674) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: INFO cinder.volume.manager [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] Determined volume DB was empty at startup.
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: DEBUG cinder.volume.manager [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] Cinder Volume DB check: vol_db_empty=True {{(pid=1579674) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: WARNING stevedore.named [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: WARNING castellan.key_manager [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: WARNING cinder.keymgr.conf_key_mgr [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume 
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: ERROR cinder.cmd.volume [None req-d89339a3-0ced-480d-b00d-e68443248b2a None None] No volume service(s) started successfully, terminating.
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]:   from cryptography.utils import int_from_bytes
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]:   from cryptography.utils import int_from_bytes
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]:   last_heartbeat = column_property(
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]:   num_hosts = column_property(
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 17:17:46 datacore-PowerEdge-R740 cinder-volume[1579674]:   num_down_hosts = column_property(
Jul 04 17:17:47 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 04 17:17:47 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jul 04 17:18:03 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1580390) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1580390) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: INFO dbcounter [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] Registered counter for database cinder
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: DEBUG oslo_db.sqlalchemy.engines [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1580390) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: DEBUG dbcounter [-] [1580390] Writer thread running {{(pid=1580390) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: INFO cinder.rpc [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: INFO cinder.rpc [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: DEBUG oslo_db.sqlalchemy.engines [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1580390) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: INFO cinder.volume.manager [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] Determined volume DB was empty at startup.
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: DEBUG cinder.volume.manager [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=1580390) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: WARNING stevedore.named [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: WARNING castellan.key_manager [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: WARNING cinder.keymgr.conf_key_mgr [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume 
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: ERROR cinder.cmd.volume [None req-86364ec2-bccd-4f02-9b88-4088ecc809e2 None None] No volume service(s) started successfully, terminating.
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]:   from cryptography.utils import int_from_bytes
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]:   from cryptography.utils import int_from_bytes
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]:   last_heartbeat = column_property(
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]:   num_hosts = column_property(
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 17:18:05 datacore-PowerEdge-R740 cinder-volume[1580390]:   num_down_hosts = column_property(
Jul 04 17:18:06 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 04 17:18:06 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
