-- Logs begin at Mon 2022-07-11 12:45:24 IST, end at Mon 2022-07-11 16:05:07 IST. --
Jul 11 16:03:46 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 11 16:03:48 datacore-PowerEdge-R740 cinder-volume[3132317]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=3132317) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 11 16:03:48 datacore-PowerEdge-R740 cinder-volume[3132317]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=3132317) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: INFO dbcounter [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] Registered counter for database cinder
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: DEBUG oslo_db.sqlalchemy.engines [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3132317) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: DEBUG dbcounter [-] [3132317] Writer thread running {{(pid=3132317) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: INFO cinder.rpc [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: INFO cinder.rpc [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: DEBUG oslo_db.sqlalchemy.engines [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3132317) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: INFO cinder.volume.manager [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] Determined volume DB was empty at startup.
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: DEBUG cinder.volume.manager [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=3132317) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: WARNING stevedore.named [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: WARNING castellan.key_manager [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: WARNING cinder.keymgr.conf_key_mgr [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 417, in create
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 158, in __init__
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume 
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: ERROR cinder.cmd.volume [None req-de8c06ab-1f7d-4acb-9bf6-09da6ef5cf92 None None] No volume service(s) started successfully, terminating.
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]:   from cryptography.utils import int_from_bytes
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]:   from cryptography.utils import int_from_bytes
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]:   last_heartbeat = column_property(
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]:   num_hosts = column_property(
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 11 16:03:49 datacore-PowerEdge-R740 cinder-volume[3132317]:   num_down_hosts = column_property(
Jul 11 16:03:49 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 11 16:03:49 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jul 11 16:04:05 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 11 16:04:07 datacore-PowerEdge-R740 cinder-volume[3133033]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=3133033) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 11 16:04:07 datacore-PowerEdge-R740 cinder-volume[3133033]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=3133033) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 11 16:04:07 datacore-PowerEdge-R740 cinder-volume[3133033]: INFO dbcounter [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] Registered counter for database cinder
Jul 11 16:04:07 datacore-PowerEdge-R740 cinder-volume[3133033]: DEBUG oslo_db.sqlalchemy.engines [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3133033) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 11 16:04:07 datacore-PowerEdge-R740 cinder-volume[3133033]: DEBUG dbcounter [-] [3133033] Writer thread running {{(pid=3133033) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 11 16:04:07 datacore-PowerEdge-R740 cinder-volume[3133033]: INFO cinder.rpc [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 11 16:04:07 datacore-PowerEdge-R740 cinder-volume[3133033]: INFO cinder.rpc [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 11 16:04:07 datacore-PowerEdge-R740 cinder-volume[3133033]: DEBUG oslo_db.sqlalchemy.engines [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3133033) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: INFO cinder.volume.manager [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] Determined volume DB was empty at startup.
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: DEBUG cinder.volume.manager [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=3133033) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: WARNING stevedore.named [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: WARNING castellan.key_manager [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: WARNING cinder.keymgr.conf_key_mgr [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 417, in create
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 158, in __init__
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume 
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: ERROR cinder.cmd.volume [None req-98a4a431-fa84-4aae-aee0-19c077428328 None None] No volume service(s) started successfully, terminating.
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]:   from cryptography.utils import int_from_bytes
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]:   from cryptography.utils import int_from_bytes
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]:   last_heartbeat = column_property(
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]:   num_hosts = column_property(
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 11 16:04:08 datacore-PowerEdge-R740 cinder-volume[3133033]:   num_down_hosts = column_property(
Jul 11 16:04:08 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 11 16:04:08 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
