-- Logs begin at Fri 2022-06-24 19:59:17 IST, end at Fri 2022-06-24 21:08:55 IST. --
Jun 24 21:08:39 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 24 21:08:41 datacore-PowerEdge-R740 cinder-volume[1770607]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1770607) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 24 21:08:41 datacore-PowerEdge-R740 cinder-volume[1770607]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1770607) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: INFO dbcounter [None req-1ee6695b-cf79-4c9a-b1d6-4be6f8c52975 None None] Registered counter for database cinder
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: DEBUG oslo_db.sqlalchemy.engines [None req-1ee6695b-cf79-4c9a-b1d6-4be6f8c52975 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1770607) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: DEBUG dbcounter [-] [1770607] Writer thread running {{(pid=1770607) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: INFO cinder.rpc [None req-1ee6695b-cf79-4c9a-b1d6-4be6f8c52975 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume [None req-1ee6695b-cf79-4c9a-b1d6-4be6f8c52975 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 220, in __init__
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/manager.py", line 185, in __init__
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/rpc.py", line 212, in __init__
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/objects/base.py", line 552, in __init__
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume 
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: ERROR cinder.cmd.volume [None req-1ee6695b-cf79-4c9a-b1d6-4be6f8c52975 None None] No volume service(s) started successfully, terminating.
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]:   from cryptography.utils import int_from_bytes
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]:   from cryptography.utils import int_from_bytes
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:135: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]:   last_heartbeat = column_property(
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:141: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]:   num_hosts = column_property(
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:148: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 24 21:08:42 datacore-PowerEdge-R740 cinder-volume[1770607]:   num_down_hosts = column_property(
Jun 24 21:08:43 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 24 21:08:43 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
