-- Logs begin at Tue 2022-07-12 19:09:06 IST, end at Tue 2022-07-12 20:13:10 IST. --
Jul 12 19:09:15 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 12 19:09:17 datacore-PowerEdge-R740 cinder-volume[3398848]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=3398848) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 12 19:09:17 datacore-PowerEdge-R740 cinder-volume[3398848]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=3398848) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 12 19:09:17 datacore-PowerEdge-R740 cinder-volume[3398848]: INFO dbcounter [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] Registered counter for database cinder
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: DEBUG oslo_db.sqlalchemy.engines [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3398848) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: DEBUG dbcounter [-] [3398848] Writer thread running {{(pid=3398848) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: INFO cinder.rpc [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: INFO cinder.rpc [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: DEBUG oslo_db.sqlalchemy.engines [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3398848) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: INFO cinder.volume.manager [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] Determined volume DB was empty at startup.
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: DEBUG cinder.volume.manager [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=3398848) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: WARNING stevedore.named [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: WARNING castellan.key_manager [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: WARNING cinder.keymgr.conf_key_mgr [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 417, in create
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 158, in __init__
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume 
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: ERROR cinder.cmd.volume [None req-e0e8c62a-3f6a-4662-97b3-ae1c2a5cbd71 None None] No volume service(s) started successfully, terminating.
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]:   from cryptography.utils import int_from_bytes
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]:   from cryptography.utils import int_from_bytes
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]:   last_heartbeat = column_property(
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]:   num_hosts = column_property(
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 12 19:09:18 datacore-PowerEdge-R740 cinder-volume[3398848]:   num_down_hosts = column_property(
Jul 12 19:09:18 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 19:09:18 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jul 12 19:14:41 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=3400452) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=3400452) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: INFO dbcounter [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] Registered counter for database cinder
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: DEBUG oslo_db.sqlalchemy.engines [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3400452) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: DEBUG dbcounter [-] [3400452] Writer thread running {{(pid=3400452) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: INFO cinder.rpc [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: INFO cinder.rpc [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: DEBUG oslo_db.sqlalchemy.engines [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3400452) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: INFO cinder.volume.manager [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] Determined volume DB was empty at startup.
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: DEBUG cinder.volume.manager [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=3400452) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: WARNING stevedore.named [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: WARNING castellan.key_manager [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: WARNING cinder.keymgr.conf_key_mgr [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 417, in create
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 158, in __init__
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume 
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: ERROR cinder.cmd.volume [None req-7a7f9530-e658-4682-b01f-4bc61ab539c6 None None] No volume service(s) started successfully, terminating.
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]:   from cryptography.utils import int_from_bytes
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]:   from cryptography.utils import int_from_bytes
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]:   last_heartbeat = column_property(
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]:   num_hosts = column_property(
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 12 19:14:43 datacore-PowerEdge-R740 cinder-volume[3400452]:   num_down_hosts = column_property(
Jul 12 19:14:44 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 19:14:44 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jul 12 19:15:00 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=3401191) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=3401191) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: INFO dbcounter [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] Registered counter for database cinder
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: DEBUG oslo_db.sqlalchemy.engines [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3401191) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: DEBUG dbcounter [-] [3401191] Writer thread running {{(pid=3401191) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: INFO cinder.rpc [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: INFO cinder.rpc [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: DEBUG oslo_db.sqlalchemy.engines [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3401191) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: INFO cinder.volume.manager [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] Determined volume DB was empty at startup.
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: DEBUG cinder.volume.manager [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] Cinder Volume DB check: vol_db_empty=True {{(pid=3401191) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: WARNING stevedore.named [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: WARNING castellan.key_manager [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 12 19:15:02 datacore-PowerEdge-R740 cinder-volume[3401191]: WARNING cinder.keymgr.conf_key_mgr [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 417, in create
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 158, in __init__
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume 
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: ERROR cinder.cmd.volume [None req-0d9668fa-5b31-47e3-8d0d-8c7f71ac09dd None None] No volume service(s) started successfully, terminating.
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]:   from cryptography.utils import int_from_bytes
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]:   from cryptography.utils import int_from_bytes
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]:   last_heartbeat = column_property(
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]:   num_hosts = column_property(
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 12 19:15:03 datacore-PowerEdge-R740 cinder-volume[3401191]:   num_down_hosts = column_property(
Jul 12 19:15:03 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 19:15:03 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
