-- Logs begin at Fri 2022-07-08 01:17:37 IST, end at Fri 2022-07-08 02:52:47 IST. --
Jul 08 02:51:27 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2362538) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2362538) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: INFO dbcounter [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] Registered counter for database cinder
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: DEBUG oslo_db.sqlalchemy.engines [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2362538) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: DEBUG dbcounter [-] [2362538] Writer thread running {{(pid=2362538) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: INFO cinder.rpc [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: INFO cinder.rpc [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: DEBUG oslo_db.sqlalchemy.engines [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2362538) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: INFO cinder.volume.manager [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] Determined volume DB was empty at startup.
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: DEBUG cinder.volume.manager [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2362538) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: WARNING stevedore.named [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: WARNING castellan.key_manager [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: WARNING cinder.keymgr.conf_key_mgr [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume 
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: ERROR cinder.cmd.volume [None req-583e5446-67ce-4c76-978c-11c408dbc156 None None] No volume service(s) started successfully, terminating.
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]:   from cryptography.utils import int_from_bytes
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]:   from cryptography.utils import int_from_bytes
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]:   last_heartbeat = column_property(
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]:   num_hosts = column_property(
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 08 02:51:29 datacore-PowerEdge-R740 cinder-volume[2362538]:   num_down_hosts = column_property(
Jul 08 02:51:30 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 08 02:51:30 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jul 08 02:51:45 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 08 02:51:47 datacore-PowerEdge-R740 cinder-volume[2363143]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2363143) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 08 02:51:47 datacore-PowerEdge-R740 cinder-volume[2363143]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2363143) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: INFO dbcounter [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] Registered counter for database cinder
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: DEBUG oslo_db.sqlalchemy.engines [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2363143) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: DEBUG dbcounter [-] [2363143] Writer thread running {{(pid=2363143) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: INFO cinder.rpc [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: INFO cinder.rpc [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: DEBUG oslo_db.sqlalchemy.engines [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2363143) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: INFO cinder.volume.manager [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] Determined volume DB was empty at startup.
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: DEBUG cinder.volume.manager [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2363143) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: WARNING stevedore.named [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: WARNING castellan.key_manager [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: WARNING cinder.keymgr.conf_key_mgr [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume 
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: ERROR cinder.cmd.volume [None req-e56b3aee-5bdd-498e-a8d5-52e8de56310d None None] No volume service(s) started successfully, terminating.
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]:   from cryptography.utils import int_from_bytes
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]:   from cryptography.utils import int_from_bytes
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]:   last_heartbeat = column_property(
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]:   num_hosts = column_property(
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 08 02:51:48 datacore-PowerEdge-R740 cinder-volume[2363143]:   num_down_hosts = column_property(
Jul 08 02:51:48 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 08 02:51:48 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
