-- Logs begin at Wed 2022-06-29 14:44:05 IST, end at Wed 2022-06-29 14:48:52 IST. --
Jun 29 14:47:29 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=279086) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=279086) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: INFO dbcounter [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] Registered counter for database cinder
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: DEBUG oslo_db.sqlalchemy.engines [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=279086) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: DEBUG dbcounter [-] [279086] Writer thread running {{(pid=279086) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: INFO cinder.rpc [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: INFO cinder.rpc [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: DEBUG oslo_db.sqlalchemy.engines [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=279086) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: INFO cinder.volume.manager [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] Determined volume DB was empty at startup.
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: DEBUG cinder.volume.manager [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] Cinder Volume DB check: vol_db_empty=True {{(pid=279086) __init__ /opt/stack/cinder/cinder/volume/manager.py:286}}
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: WARNING stevedore.named [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: WARNING castellan.key_manager [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: WARNING cinder.keymgr.conf_key_mgr [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 309, in __init__
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume 
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: ERROR cinder.cmd.volume [None req-e5cc9180-c229-455f-a90e-44fcefbf9a8a None None] No volume service(s) started successfully, terminating.
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]:   from cryptography.utils import int_from_bytes
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]:   from cryptography.utils import int_from_bytes
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]:   last_heartbeat = column_property(
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]:   num_hosts = column_property(
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 29 14:47:32 datacore-PowerEdge-R740 cinder-volume[279086]:   num_down_hosts = column_property(
Jun 29 14:47:33 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 29 14:47:33 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jun 29 14:47:49 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 29 14:47:51 datacore-PowerEdge-R740 cinder-volume[279703]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=279703) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 29 14:47:51 datacore-PowerEdge-R740 cinder-volume[279703]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=279703) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: INFO dbcounter [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] Registered counter for database cinder
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: DEBUG oslo_db.sqlalchemy.engines [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=279703) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: DEBUG dbcounter [-] [279703] Writer thread running {{(pid=279703) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: INFO cinder.rpc [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: INFO cinder.rpc [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: DEBUG oslo_db.sqlalchemy.engines [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=279703) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: INFO cinder.volume.manager [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] Determined volume DB was empty at startup.
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: DEBUG cinder.volume.manager [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=279703) __init__ /opt/stack/cinder/cinder/volume/manager.py:286}}
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: WARNING stevedore.named [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: WARNING castellan.key_manager [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: WARNING cinder.keymgr.conf_key_mgr [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 309, in __init__
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume 
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: ERROR cinder.cmd.volume [None req-33fc882d-832c-46a8-adfc-c19cc1fed176 None None] No volume service(s) started successfully, terminating.
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]:   from cryptography.utils import int_from_bytes
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]:   from cryptography.utils import int_from_bytes
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]:   last_heartbeat = column_property(
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]:   num_hosts = column_property(
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 29 14:47:52 datacore-PowerEdge-R740 cinder-volume[279703]:   num_down_hosts = column_property(
Jun 29 14:47:53 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 29 14:47:53 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
