-- Logs begin at Tue 2022-06-21 07:52:05 IST, end at Tue 2022-06-21 07:53:15 IST. --
Jun 21 07:52:13 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 21 07:52:15 datacore-PowerEdge-R740 cinder-volume[904934]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=904934) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 21 07:52:15 datacore-PowerEdge-R740 cinder-volume[904934]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=904934) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 21 07:52:15 datacore-PowerEdge-R740 cinder-volume[904934]: INFO dbcounter [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] Registered counter for database cinder
Jun 21 07:52:15 datacore-PowerEdge-R740 cinder-volume[904934]: DEBUG oslo_db.sqlalchemy.engines [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=904934) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 21 07:52:15 datacore-PowerEdge-R740 cinder-volume[904934]: DEBUG dbcounter [-] [904934] Writer thread running {{(pid=904934) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: INFO cinder.rpc [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: INFO cinder.rpc [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: DEBUG oslo_db.sqlalchemy.engines [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=904934) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: INFO cinder.volume.manager [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] Determined volume DB was not empty at startup.
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: DEBUG cinder.volume.manager [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] Cinder Volume DB check: vol_db_empty=False {{(pid=904934) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: WARNING stevedore.named [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: WARNING castellan.key_manager [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: WARNING cinder.keymgr.conf_key_mgr [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume 
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: ERROR cinder.cmd.volume [None req-79be7832-9e2f-47d0-80b1-a5ed3c74639d None None] No volume service(s) started successfully, terminating.
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]:   from cryptography.utils import int_from_bytes
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]:   from cryptography.utils import int_from_bytes
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]:   last_heartbeat = column_property(
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]:   num_hosts = column_property(
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 21 07:52:16 datacore-PowerEdge-R740 cinder-volume[904934]:   num_down_hosts = column_property(
Jun 21 07:52:16 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 21 07:52:16 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
