-- Logs begin at Thu 2022-07-07 12:06:44 IST, end at Thu 2022-07-07 15:07:11 IST. --
Jul 07 15:05:50 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 07 15:05:52 datacore-PowerEdge-R740 cinder-volume[2242035]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2242035) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 07 15:05:52 datacore-PowerEdge-R740 cinder-volume[2242035]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2242035) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: INFO dbcounter [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] Registered counter for database cinder
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: DEBUG oslo_db.sqlalchemy.engines [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2242035) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: DEBUG dbcounter [-] [2242035] Writer thread running {{(pid=2242035) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: INFO cinder.rpc [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: INFO cinder.rpc [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: DEBUG oslo_db.sqlalchemy.engines [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2242035) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: INFO cinder.volume.manager [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] Determined volume DB was empty at startup.
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: DEBUG cinder.volume.manager [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2242035) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: WARNING stevedore.named [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: WARNING castellan.key_manager [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: WARNING cinder.keymgr.conf_key_mgr [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume 
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: ERROR cinder.cmd.volume [None req-10c43c1a-5a12-4de9-898c-9eec3c187d3d None None] No volume service(s) started successfully, terminating.
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]:   from cryptography.utils import int_from_bytes
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]:   from cryptography.utils import int_from_bytes
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]:   last_heartbeat = column_property(
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]:   num_hosts = column_property(
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 07 15:05:53 datacore-PowerEdge-R740 cinder-volume[2242035]:   num_down_hosts = column_property(
Jul 07 15:05:54 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 07 15:05:54 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jul 07 15:06:07 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2242744) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2242744) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: INFO dbcounter [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] Registered counter for database cinder
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: DEBUG oslo_db.sqlalchemy.engines [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2242744) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: DEBUG dbcounter [-] [2242744] Writer thread running {{(pid=2242744) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: INFO cinder.rpc [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: INFO cinder.rpc [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: DEBUG oslo_db.sqlalchemy.engines [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2242744) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: INFO cinder.volume.manager [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] Determined volume DB was empty at startup.
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: DEBUG cinder.volume.manager [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2242744) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: WARNING stevedore.named [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: WARNING castellan.key_manager [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: WARNING cinder.keymgr.conf_key_mgr [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume 
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: ERROR cinder.cmd.volume [None req-6ee378a6-cd74-487e-91e2-03a764ed1ebc None None] No volume service(s) started successfully, terminating.
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]:   from cryptography.utils import int_from_bytes
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]:   from cryptography.utils import int_from_bytes
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]:   last_heartbeat = column_property(
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]:   num_hosts = column_property(
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 07 15:06:10 datacore-PowerEdge-R740 cinder-volume[2242744]:   num_down_hosts = column_property(
Jul 07 15:06:11 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 07 15:06:11 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
