-- Logs begin at Tue 2022-06-21 15:21:33 IST, end at Tue 2022-06-21 19:49:22 IST. --
Jun 21 19:48:04 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1013052) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1013052) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: INFO dbcounter [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] Registered counter for database cinder
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: DEBUG oslo_db.sqlalchemy.engines [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1013052) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: DEBUG dbcounter [-] [1013052] Writer thread running {{(pid=1013052) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: INFO cinder.rpc [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: INFO cinder.rpc [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: DEBUG oslo_db.sqlalchemy.engines [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1013052) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: INFO cinder.volume.manager [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] Determined volume DB was not empty at startup.
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: DEBUG cinder.volume.manager [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] Cinder Volume DB check: vol_db_empty=False {{(pid=1013052) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: WARNING stevedore.named [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: WARNING castellan.key_manager [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: WARNING cinder.keymgr.conf_key_mgr [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume 
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: ERROR cinder.cmd.volume [None req-67c62035-3900-4b2c-bb56-23d232e83c62 None None] No volume service(s) started successfully, terminating.
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]:   from cryptography.utils import int_from_bytes
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]:   from cryptography.utils import int_from_bytes
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]:   last_heartbeat = column_property(
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]:   num_hosts = column_property(
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 21 19:48:06 datacore-PowerEdge-R740 cinder-volume[1013052]:   num_down_hosts = column_property(
Jun 21 19:48:07 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 21 19:48:07 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jun 21 19:48:19 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 21 19:48:21 datacore-PowerEdge-R740 cinder-volume[1013725]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1013725) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 21 19:48:21 datacore-PowerEdge-R740 cinder-volume[1013725]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1013725) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: INFO dbcounter [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] Registered counter for database cinder
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: DEBUG oslo_db.sqlalchemy.engines [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1013725) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: DEBUG dbcounter [-] [1013725] Writer thread running {{(pid=1013725) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: INFO cinder.rpc [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: INFO cinder.rpc [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: DEBUG oslo_db.sqlalchemy.engines [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1013725) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: INFO cinder.volume.manager [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] Determined volume DB was not empty at startup.
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: DEBUG cinder.volume.manager [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] Cinder Volume DB check: vol_db_empty=False {{(pid=1013725) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: WARNING stevedore.named [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: WARNING castellan.key_manager [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: WARNING cinder.keymgr.conf_key_mgr [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume 
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: ERROR cinder.cmd.volume [None req-5ce7a122-22bc-4eeb-a96a-90440f57a4ed None None] No volume service(s) started successfully, terminating.
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]:   from cryptography.utils import int_from_bytes
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]:   from cryptography.utils import int_from_bytes
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]:   last_heartbeat = column_property(
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]:   num_hosts = column_property(
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 21 19:48:22 datacore-PowerEdge-R740 cinder-volume[1013725]:   num_down_hosts = column_property(
Jun 21 19:48:23 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 21 19:48:23 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
