-- Logs begin at Wed 2022-06-22 13:47:27 IST, end at Wed 2022-06-22 13:51:33 IST. --
Jun 22 13:50:14 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 22 13:50:16 datacore-PowerEdge-R740 cinder-volume[1212620]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1212620) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 22 13:50:16 datacore-PowerEdge-R740 cinder-volume[1212620]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1212620) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: INFO dbcounter [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] Registered counter for database cinder
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: DEBUG oslo_db.sqlalchemy.engines [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1212620) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: DEBUG dbcounter [-] [1212620] Writer thread running {{(pid=1212620) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: INFO cinder.rpc [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: INFO cinder.rpc [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: DEBUG oslo_db.sqlalchemy.engines [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1212620) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: INFO cinder.volume.manager [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] Determined volume DB was not empty at startup.
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: DEBUG cinder.volume.manager [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] Cinder Volume DB check: vol_db_empty=False {{(pid=1212620) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: WARNING stevedore.named [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: WARNING castellan.key_manager [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: WARNING cinder.keymgr.conf_key_mgr [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume 
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: ERROR cinder.cmd.volume [None req-058f064d-022a-4a60-9fe7-1cf2550f28de None None] No volume service(s) started successfully, terminating.
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]:   from cryptography.utils import int_from_bytes
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]:   from cryptography.utils import int_from_bytes
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]:   last_heartbeat = column_property(
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]:   num_hosts = column_property(
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:50:17 datacore-PowerEdge-R740 cinder-volume[1212620]:   num_down_hosts = column_property(
Jun 22 13:50:17 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 22 13:50:17 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jun 22 13:50:30 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 22 13:50:32 datacore-PowerEdge-R740 cinder-volume[1213194]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1213194) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 22 13:50:32 datacore-PowerEdge-R740 cinder-volume[1213194]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1213194) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: INFO dbcounter [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] Registered counter for database cinder
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: DEBUG oslo_db.sqlalchemy.engines [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1213194) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: DEBUG dbcounter [-] [1213194] Writer thread running {{(pid=1213194) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: INFO cinder.rpc [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: INFO cinder.rpc [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: DEBUG oslo_db.sqlalchemy.engines [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1213194) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: INFO cinder.volume.manager [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] Determined volume DB was not empty at startup.
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: DEBUG cinder.volume.manager [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] Cinder Volume DB check: vol_db_empty=False {{(pid=1213194) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: WARNING stevedore.named [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: WARNING castellan.key_manager [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: WARNING cinder.keymgr.conf_key_mgr [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume 
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: ERROR cinder.cmd.volume [None req-69b1b99a-4b9d-4af5-87de-1f0bed4d2e70 None None] No volume service(s) started successfully, terminating.
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]:   from cryptography.utils import int_from_bytes
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]:   from cryptography.utils import int_from_bytes
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]:   last_heartbeat = column_property(
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]:   num_hosts = column_property(
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:50:33 datacore-PowerEdge-R740 cinder-volume[1213194]:   num_down_hosts = column_property(
Jun 22 13:50:33 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 22 13:50:33 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
