-- Logs begin at Wed 2022-06-22 13:44:07 IST, end at Wed 2022-06-22 13:48:22 IST. --
Jun 22 13:44:15 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1209351) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1209351) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: INFO dbcounter [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] Registered counter for database cinder
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: DEBUG oslo_db.sqlalchemy.engines [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1209351) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: DEBUG dbcounter [-] [1209351] Writer thread running {{(pid=1209351) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: INFO cinder.rpc [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: INFO cinder.rpc [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: DEBUG oslo_db.sqlalchemy.engines [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1209351) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: INFO cinder.volume.manager [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] Determined volume DB was not empty at startup.
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: DEBUG cinder.volume.manager [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] Cinder Volume DB check: vol_db_empty=False {{(pid=1209351) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: WARNING stevedore.named [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: WARNING castellan.key_manager [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: WARNING cinder.keymgr.conf_key_mgr [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume 
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: ERROR cinder.cmd.volume [None req-9d4ba723-855c-4872-934e-3ca102e644d8 None None] No volume service(s) started successfully, terminating.
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]:   from cryptography.utils import int_from_bytes
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]:   from cryptography.utils import int_from_bytes
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]:   last_heartbeat = column_property(
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]:   num_hosts = column_property(
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:44:17 datacore-PowerEdge-R740 cinder-volume[1209351]:   num_down_hosts = column_property(
Jun 22 13:44:18 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 22 13:44:18 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jun 22 13:47:04 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 22 13:47:06 datacore-PowerEdge-R740 cinder-volume[1210696]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1210696) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 22 13:47:06 datacore-PowerEdge-R740 cinder-volume[1210696]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1210696) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 22 13:47:06 datacore-PowerEdge-R740 cinder-volume[1210696]: INFO dbcounter [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] Registered counter for database cinder
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: DEBUG oslo_db.sqlalchemy.engines [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1210696) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: DEBUG dbcounter [-] [1210696] Writer thread running {{(pid=1210696) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: INFO cinder.rpc [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: INFO cinder.rpc [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: DEBUG oslo_db.sqlalchemy.engines [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1210696) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: INFO cinder.volume.manager [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] Determined volume DB was not empty at startup.
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: DEBUG cinder.volume.manager [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] Cinder Volume DB check: vol_db_empty=False {{(pid=1210696) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: WARNING stevedore.named [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: WARNING castellan.key_manager [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: WARNING cinder.keymgr.conf_key_mgr [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume 
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: ERROR cinder.cmd.volume [None req-9c28865c-dd34-4af8-aa87-8f50e4e69182 None None] No volume service(s) started successfully, terminating.
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]:   from cryptography.utils import int_from_bytes
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]:   from cryptography.utils import int_from_bytes
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]:   last_heartbeat = column_property(
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]:   num_hosts = column_property(
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:47:07 datacore-PowerEdge-R740 cinder-volume[1210696]:   num_down_hosts = column_property(
Jun 22 13:47:07 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 22 13:47:07 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jun 22 13:47:20 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1211272) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1211272) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: INFO dbcounter [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] Registered counter for database cinder
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: DEBUG oslo_db.sqlalchemy.engines [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1211272) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: DEBUG dbcounter [-] [1211272] Writer thread running {{(pid=1211272) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: INFO cinder.rpc [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: INFO cinder.rpc [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: DEBUG oslo_db.sqlalchemy.engines [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1211272) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: INFO cinder.volume.manager [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] Determined volume DB was not empty at startup.
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: DEBUG cinder.volume.manager [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] Cinder Volume DB check: vol_db_empty=False {{(pid=1211272) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: WARNING stevedore.named [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: WARNING castellan.key_manager [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: WARNING cinder.keymgr.conf_key_mgr [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume 
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: ERROR cinder.cmd.volume [None req-99a68e11-ef44-4c5a-aca2-1f652c843190 None None] No volume service(s) started successfully, terminating.
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]:   from cryptography.utils import int_from_bytes
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]:   from cryptography.utils import int_from_bytes
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]:   last_heartbeat = column_property(
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]:   num_hosts = column_property(
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 22 13:47:22 datacore-PowerEdge-R740 cinder-volume[1211272]:   num_down_hosts = column_property(
Jun 22 13:47:23 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 22 13:47:23 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
