-- Logs begin at Mon 2022-07-04 17:18:11 IST, end at Mon 2022-07-04 21:35:31 IST. --
Jul 04 21:34:11 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1617751) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1617751) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: INFO dbcounter [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] Registered counter for database cinder
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: DEBUG oslo_db.sqlalchemy.engines [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1617751) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: DEBUG dbcounter [-] [1617751] Writer thread running {{(pid=1617751) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: INFO cinder.rpc [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: INFO cinder.rpc [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: DEBUG oslo_db.sqlalchemy.engines [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1617751) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: INFO cinder.volume.manager [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] Determined volume DB was empty at startup.
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: DEBUG cinder.volume.manager [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] Cinder Volume DB check: vol_db_empty=True {{(pid=1617751) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: WARNING stevedore.named [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: WARNING castellan.key_manager [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: WARNING cinder.keymgr.conf_key_mgr [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume 
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: ERROR cinder.cmd.volume [None req-d68aeb96-531d-49eb-b667-0471782a836d None None] No volume service(s) started successfully, terminating.
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]:   from cryptography.utils import int_from_bytes
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]:   from cryptography.utils import int_from_bytes
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]:   last_heartbeat = column_property(
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]:   num_hosts = column_property(
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 21:34:13 datacore-PowerEdge-R740 cinder-volume[1617751]:   num_down_hosts = column_property(
Jul 04 21:34:14 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 04 21:34:14 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jul 04 21:34:29 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 04 21:34:31 datacore-PowerEdge-R740 cinder-volume[1618362]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1618362) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 04 21:34:31 datacore-PowerEdge-R740 cinder-volume[1618362]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1618362) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 04 21:34:31 datacore-PowerEdge-R740 cinder-volume[1618362]: INFO dbcounter [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] Registered counter for database cinder
Jul 04 21:34:31 datacore-PowerEdge-R740 cinder-volume[1618362]: DEBUG oslo_db.sqlalchemy.engines [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1618362) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 04 21:34:31 datacore-PowerEdge-R740 cinder-volume[1618362]: DEBUG dbcounter [-] [1618362] Writer thread running {{(pid=1618362) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: INFO cinder.rpc [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: INFO cinder.rpc [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: DEBUG oslo_db.sqlalchemy.engines [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1618362) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: INFO cinder.volume.manager [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] Determined volume DB was empty at startup.
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: DEBUG cinder.volume.manager [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=1618362) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: WARNING stevedore.named [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: WARNING castellan.key_manager [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: WARNING cinder.keymgr.conf_key_mgr [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume 
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: ERROR cinder.cmd.volume [None req-c0f52420-f94e-404e-b0fc-8779f92977e3 None None] No volume service(s) started successfully, terminating.
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]:   from cryptography.utils import int_from_bytes
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]:   from cryptography.utils import int_from_bytes
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]:   last_heartbeat = column_property(
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]:   num_hosts = column_property(
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 04 21:34:32 datacore-PowerEdge-R740 cinder-volume[1618362]:   num_down_hosts = column_property(
Jul 04 21:34:32 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 04 21:34:32 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
