-- Logs begin at Mon 2022-06-27 20:36:16 IST, end at Mon 2022-06-27 23:10:10 IST. --
Jun 27 23:08:53 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2434227) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2434227) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: INFO dbcounter [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] Registered counter for database cinder
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: DEBUG oslo_db.sqlalchemy.engines [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2434227) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: DEBUG dbcounter [-] [2434227] Writer thread running {{(pid=2434227) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: INFO cinder.rpc [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: INFO cinder.rpc [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: DEBUG oslo_db.sqlalchemy.engines [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2434227) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: INFO cinder.volume.manager [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] Determined volume DB was not empty at startup.
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: DEBUG cinder.volume.manager [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] Cinder Volume DB check: vol_db_empty=False {{(pid=2434227) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: WARNING stevedore.named [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: WARNING castellan.key_manager [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: WARNING cinder.keymgr.conf_key_mgr [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume 
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: ERROR cinder.cmd.volume [None req-7e738bc8-6d7f-47c7-8f11-e82551f52c84 None None] No volume service(s) started successfully, terminating.
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]:   from cryptography.utils import int_from_bytes
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]:   from cryptography.utils import int_from_bytes
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]:   last_heartbeat = column_property(
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]:   num_hosts = column_property(
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 27 23:08:55 datacore-PowerEdge-R740 cinder-volume[2434227]:   num_down_hosts = column_property(
Jun 27 23:08:56 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 27 23:08:56 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jun 27 23:09:08 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2434807) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2434807) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: INFO dbcounter [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] Registered counter for database cinder
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: DEBUG oslo_db.sqlalchemy.engines [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2434807) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: DEBUG dbcounter [-] [2434807] Writer thread running {{(pid=2434807) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: INFO cinder.rpc [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: INFO cinder.rpc [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: DEBUG oslo_db.sqlalchemy.engines [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2434807) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: INFO cinder.volume.manager [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] Determined volume DB was not empty at startup.
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: DEBUG cinder.volume.manager [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] Cinder Volume DB check: vol_db_empty=False {{(pid=2434807) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: WARNING stevedore.named [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: WARNING castellan.key_manager [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: WARNING cinder.keymgr.conf_key_mgr [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume 
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: ERROR cinder.cmd.volume [None req-93b906d6-bbc4-42bf-bb88-5569b8b850dd None None] No volume service(s) started successfully, terminating.
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]:   from cryptography.utils import int_from_bytes
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]:   from cryptography.utils import int_from_bytes
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]:   last_heartbeat = column_property(
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]:   num_hosts = column_property(
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 27 23:09:10 datacore-PowerEdge-R740 cinder-volume[2434807]:   num_down_hosts = column_property(
Jun 27 23:09:11 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 27 23:09:11 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
