-- Logs begin at Tue 2022-06-28 22:28:20 IST, end at Tue 2022-06-28 23:54:41 IST. --
Jun 28 23:54:22 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 28 23:54:24 datacore-PowerEdge-R740 cinder-volume[134270]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=134270) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 28 23:54:24 datacore-PowerEdge-R740 cinder-volume[134270]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=134270) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 28 23:54:24 datacore-PowerEdge-R740 cinder-volume[134270]: INFO dbcounter [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] Registered counter for database cinder
Jun 28 23:54:24 datacore-PowerEdge-R740 cinder-volume[134270]: DEBUG oslo_db.sqlalchemy.engines [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=134270) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 28 23:54:24 datacore-PowerEdge-R740 cinder-volume[134270]: DEBUG dbcounter [-] [134270] Writer thread running {{(pid=134270) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: INFO cinder.rpc [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: INFO cinder.rpc [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: DEBUG oslo_db.sqlalchemy.engines [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=134270) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: INFO cinder.volume.manager [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] Determined volume DB was empty at startup.
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: DEBUG cinder.volume.manager [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=134270) __init__ /opt/stack/cinder/cinder/volume/manager.py:281}}
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: WARNING stevedore.named [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: WARNING castellan.key_manager [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: WARNING cinder.keymgr.conf_key_mgr [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 305, in __init__
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume 
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: ERROR cinder.cmd.volume [None req-f440555c-3c5c-4fe0-93a4-74c59ab563e2 None None] No volume service(s) started successfully, terminating.
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]:   from cryptography.utils import int_from_bytes
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]:   from cryptography.utils import int_from_bytes
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:138: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]:   last_heartbeat = column_property(
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:144: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]:   num_hosts = column_property(
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:151: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 28 23:54:25 datacore-PowerEdge-R740 cinder-volume[134270]:   num_down_hosts = column_property(
Jun 28 23:54:25 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 28 23:54:25 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
