-- Logs begin at Sat 2022-06-25 13:42:50 IST, end at Sat 2022-06-25 20:48:30 IST. --
Jun 25 20:47:13 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 25 20:47:15 datacore-PowerEdge-R740 cinder-volume[1983550]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1983550) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 25 20:47:15 datacore-PowerEdge-R740 cinder-volume[1983550]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1983550) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 25 20:47:15 datacore-PowerEdge-R740 cinder-volume[1983550]: INFO dbcounter [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] Registered counter for database cinder
Jun 25 20:47:15 datacore-PowerEdge-R740 cinder-volume[1983550]: DEBUG oslo_db.sqlalchemy.engines [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1983550) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 25 20:47:15 datacore-PowerEdge-R740 cinder-volume[1983550]: DEBUG dbcounter [-] [1983550] Writer thread running {{(pid=1983550) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 25 20:47:15 datacore-PowerEdge-R740 cinder-volume[1983550]: INFO cinder.rpc [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 25 20:47:15 datacore-PowerEdge-R740 cinder-volume[1983550]: INFO cinder.rpc [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 25 20:47:15 datacore-PowerEdge-R740 cinder-volume[1983550]: DEBUG oslo_db.sqlalchemy.engines [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1983550) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: INFO cinder.volume.manager [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] Determined volume DB was not empty at startup.
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: DEBUG cinder.volume.manager [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] Cinder Volume DB check: vol_db_empty=False {{(pid=1983550) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: WARNING stevedore.named [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: WARNING castellan.key_manager [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: WARNING cinder.keymgr.conf_key_mgr [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume 
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: ERROR cinder.cmd.volume [None req-81ce1d42-caa0-4392-9875-7636cfe6ff1b None None] No volume service(s) started successfully, terminating.
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]:   from cryptography.utils import int_from_bytes
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]:   from cryptography.utils import int_from_bytes
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]:   last_heartbeat = column_property(
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]:   num_hosts = column_property(
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 20:47:16 datacore-PowerEdge-R740 cinder-volume[1983550]:   num_down_hosts = column_property(
Jun 25 20:47:16 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 25 20:47:16 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jun 25 20:47:28 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 25 20:47:30 datacore-PowerEdge-R740 cinder-volume[1984229]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1984229) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 25 20:47:30 datacore-PowerEdge-R740 cinder-volume[1984229]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1984229) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 25 20:47:30 datacore-PowerEdge-R740 cinder-volume[1984229]: INFO dbcounter [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] Registered counter for database cinder
Jun 25 20:47:30 datacore-PowerEdge-R740 cinder-volume[1984229]: DEBUG oslo_db.sqlalchemy.engines [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1984229) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 25 20:47:30 datacore-PowerEdge-R740 cinder-volume[1984229]: DEBUG dbcounter [-] [1984229] Writer thread running {{(pid=1984229) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 25 20:47:30 datacore-PowerEdge-R740 cinder-volume[1984229]: INFO cinder.rpc [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 25 20:47:30 datacore-PowerEdge-R740 cinder-volume[1984229]: INFO cinder.rpc [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 25 20:47:30 datacore-PowerEdge-R740 cinder-volume[1984229]: DEBUG oslo_db.sqlalchemy.engines [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1984229) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: INFO cinder.volume.manager [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] Determined volume DB was not empty at startup.
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: DEBUG cinder.volume.manager [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] Cinder Volume DB check: vol_db_empty=False {{(pid=1984229) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: WARNING stevedore.named [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: WARNING castellan.key_manager [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: WARNING cinder.keymgr.conf_key_mgr [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume 
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: ERROR cinder.cmd.volume [None req-92c0df8a-8c74-403f-b7eb-3543f47d6c1d None None] No volume service(s) started successfully, terminating.
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]:   from cryptography.utils import int_from_bytes
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]:   from cryptography.utils import int_from_bytes
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]:   last_heartbeat = column_property(
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]:   num_hosts = column_property(
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 20:47:31 datacore-PowerEdge-R740 cinder-volume[1984229]:   num_down_hosts = column_property(
Jun 25 20:47:31 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 25 20:47:31 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
