-- Logs begin at Wed 2022-06-29 22:44:10 IST, end at Thu 2022-06-30 01:21:38 IST. --
Jun 30 01:20:16 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 30 01:20:18 datacore-PowerEdge-R740 cinder-volume[383723]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=383723) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 30 01:20:18 datacore-PowerEdge-R740 cinder-volume[383723]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=383723) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 30 01:20:18 datacore-PowerEdge-R740 cinder-volume[383723]: INFO dbcounter [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] Registered counter for database cinder
Jun 30 01:20:18 datacore-PowerEdge-R740 cinder-volume[383723]: DEBUG oslo_db.sqlalchemy.engines [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=383723) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 30 01:20:18 datacore-PowerEdge-R740 cinder-volume[383723]: DEBUG dbcounter [-] [383723] Writer thread running {{(pid=383723) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 30 01:20:18 datacore-PowerEdge-R740 cinder-volume[383723]: INFO cinder.rpc [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 30 01:20:18 datacore-PowerEdge-R740 cinder-volume[383723]: INFO cinder.rpc [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 30 01:20:18 datacore-PowerEdge-R740 cinder-volume[383723]: DEBUG oslo_db.sqlalchemy.engines [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=383723) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: INFO cinder.volume.manager [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] Determined volume DB was empty at startup.
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: DEBUG cinder.volume.manager [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=383723) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: WARNING stevedore.named [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: WARNING castellan.key_manager [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: WARNING cinder.keymgr.conf_key_mgr [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume 
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: ERROR cinder.cmd.volume [None req-91c04596-afb3-4ffc-92c9-727d4bf8a995 None None] No volume service(s) started successfully, terminating.
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]:   from cryptography.utils import int_from_bytes
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]:   from cryptography.utils import int_from_bytes
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]:   last_heartbeat = column_property(
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]:   num_hosts = column_property(
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 30 01:20:19 datacore-PowerEdge-R740 cinder-volume[383723]:   num_down_hosts = column_property(
Jun 30 01:20:19 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 30 01:20:19 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jun 30 01:20:35 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=384340) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=384340) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: INFO dbcounter [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] Registered counter for database cinder
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: DEBUG oslo_db.sqlalchemy.engines [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=384340) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: DEBUG dbcounter [-] [384340] Writer thread running {{(pid=384340) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: INFO cinder.rpc [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: INFO cinder.rpc [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: DEBUG oslo_db.sqlalchemy.engines [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=384340) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: INFO cinder.volume.manager [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] Determined volume DB was empty at startup.
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: DEBUG cinder.volume.manager [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] Cinder Volume DB check: vol_db_empty=True {{(pid=384340) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: WARNING stevedore.named [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: WARNING castellan.key_manager [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: WARNING cinder.keymgr.conf_key_mgr [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume 
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: ERROR cinder.cmd.volume [None req-ec7e96cf-660d-4acc-8f27-fa3cc1c458ae None None] No volume service(s) started successfully, terminating.
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]:   from cryptography.utils import int_from_bytes
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]:   from cryptography.utils import int_from_bytes
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]:   last_heartbeat = column_property(
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]:   num_hosts = column_property(
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 30 01:20:37 datacore-PowerEdge-R740 cinder-volume[384340]:   num_down_hosts = column_property(
Jun 30 01:20:38 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 30 01:20:38 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
