-- Logs begin at Fri 2022-07-08 21:01:39 IST, end at Sat 2022-07-09 01:03:16 IST. --
Jul 09 01:01:55 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2576849) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2576849) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: INFO dbcounter [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] Registered counter for database cinder
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: DEBUG oslo_db.sqlalchemy.engines [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2576849) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: DEBUG dbcounter [-] [2576849] Writer thread running {{(pid=2576849) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: INFO cinder.rpc [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: INFO cinder.rpc [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: DEBUG oslo_db.sqlalchemy.engines [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2576849) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: INFO cinder.volume.manager [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] Determined volume DB was empty at startup.
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: DEBUG cinder.volume.manager [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2576849) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: WARNING stevedore.named [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: WARNING castellan.key_manager [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: WARNING cinder.keymgr.conf_key_mgr [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 417, in create
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 158, in __init__
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume 
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: ERROR cinder.cmd.volume [None req-2c597d62-1bbc-4c36-81e3-71983477dcac None None] No volume service(s) started successfully, terminating.
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]:   from cryptography.utils import int_from_bytes
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]:   from cryptography.utils import int_from_bytes
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]:   last_heartbeat = column_property(
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]:   num_hosts = column_property(
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 09 01:01:57 datacore-PowerEdge-R740 cinder-volume[2576849]:   num_down_hosts = column_property(
Jul 09 01:01:58 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 09 01:01:58 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jul 09 01:02:14 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2577575) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2577575) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: INFO dbcounter [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] Registered counter for database cinder
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: DEBUG oslo_db.sqlalchemy.engines [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2577575) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: DEBUG dbcounter [-] [2577575] Writer thread running {{(pid=2577575) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: INFO cinder.rpc [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: INFO cinder.rpc [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: DEBUG oslo_db.sqlalchemy.engines [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2577575) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: INFO cinder.volume.manager [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] Determined volume DB was empty at startup.
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: DEBUG cinder.volume.manager [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2577575) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: WARNING stevedore.named [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: WARNING castellan.key_manager [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: WARNING cinder.keymgr.conf_key_mgr [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 417, in create
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 158, in __init__
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume 
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: ERROR cinder.cmd.volume [None req-cfff2c3d-f714-41c9-b233-bafa113d0f7d None None] No volume service(s) started successfully, terminating.
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]:   from cryptography.utils import int_from_bytes
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]:   from cryptography.utils import int_from_bytes
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]:   last_heartbeat = column_property(
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]:   num_hosts = column_property(
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 09 01:02:16 datacore-PowerEdge-R740 cinder-volume[2577575]:   num_down_hosts = column_property(
Jul 09 01:02:17 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 09 01:02:17 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
