-- Logs begin at Sat 2022-06-25 00:49:33 IST, end at Sat 2022-06-25 03:15:50 IST. --
Jun 25 01:12:45 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 25 01:12:47 datacore-PowerEdge-R740 cinder-volume[1812756]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1812756) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 25 01:12:47 datacore-PowerEdge-R740 cinder-volume[1812756]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1812756) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: INFO dbcounter [None req-c230fe93-a17a-4655-9a34-9fbac6ac281f None None] Registered counter for database cinder
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: DEBUG oslo_db.sqlalchemy.engines [None req-c230fe93-a17a-4655-9a34-9fbac6ac281f None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1812756) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: DEBUG dbcounter [-] [1812756] Writer thread running {{(pid=1812756) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: INFO cinder.rpc [None req-c230fe93-a17a-4655-9a34-9fbac6ac281f None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume [None req-c230fe93-a17a-4655-9a34-9fbac6ac281f None None] Volume service hostgroup@datacore_iscsi1 failed to start.: cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 220, in __init__
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume     super(VolumeManager, self).__init__(  # type: ignore
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/manager.py", line 185, in __init__
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume     self.scheduler_rpcapi = scheduler_rpcapi.SchedulerAPI()
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/rpc.py", line 212, in __init__
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume     serializer = base.CinderObjectSerializer(obj_version_cap)
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/objects/base.py", line 552, in __init__
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume     raise exception.CappedVersionUnknown(version=version_cap)
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume cinder.exception.CappedVersionUnknown: Unrecoverable Error: Versioned Objects in DB are capped to unknown version 1.39. Most likely your environment contains only new services and you're trying to start an older one. Use `cinder-manage service list` to check that and upgrade this service.
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume 
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: ERROR cinder.cmd.volume [None req-c230fe93-a17a-4655-9a34-9fbac6ac281f None None] No volume service(s) started successfully, terminating.
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]:   from cryptography.utils import int_from_bytes
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]:   from cryptography.utils import int_from_bytes
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:135: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]:   last_heartbeat = column_property(
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:141: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]:   num_hosts = column_property(
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:148: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 01:12:48 datacore-PowerEdge-R740 cinder-volume[1812756]:   num_down_hosts = column_property(
Jun 25 01:12:49 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 25 01:12:49 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jun 25 03:14:31 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1830770) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1830770) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: INFO dbcounter [None req-075199b9-86db-4455-8927-80249f6074da None None] Registered counter for database cinder
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: DEBUG oslo_db.sqlalchemy.engines [None req-075199b9-86db-4455-8927-80249f6074da None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1830770) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: DEBUG dbcounter [-] [1830770] Writer thread running {{(pid=1830770) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: INFO cinder.rpc [None req-075199b9-86db-4455-8927-80249f6074da None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: INFO cinder.rpc [None req-075199b9-86db-4455-8927-80249f6074da None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: DEBUG oslo_db.sqlalchemy.engines [None req-075199b9-86db-4455-8927-80249f6074da None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1830770) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: INFO cinder.volume.manager [None req-075199b9-86db-4455-8927-80249f6074da None None] Determined volume DB was not empty at startup.
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: DEBUG cinder.volume.manager [None req-075199b9-86db-4455-8927-80249f6074da None None] Cinder Volume DB check: vol_db_empty=False {{(pid=1830770) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: WARNING stevedore.named [None req-075199b9-86db-4455-8927-80249f6074da None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 25 03:14:34 datacore-PowerEdge-R740 cinder-volume[1830770]: WARNING castellan.key_manager [None req-075199b9-86db-4455-8927-80249f6074da None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: WARNING cinder.keymgr.conf_key_mgr [None req-075199b9-86db-4455-8927-80249f6074da None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume [None req-075199b9-86db-4455-8927-80249f6074da None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume 
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: ERROR cinder.cmd.volume [None req-075199b9-86db-4455-8927-80249f6074da None None] No volume service(s) started successfully, terminating.
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]:   from cryptography.utils import int_from_bytes
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]:   from cryptography.utils import int_from_bytes
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]:   last_heartbeat = column_property(
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]:   num_hosts = column_property(
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 03:14:35 datacore-PowerEdge-R740 cinder-volume[1830770]:   num_down_hosts = column_property(
Jun 25 03:14:35 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 25 03:14:35 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
Jun 25 03:14:47 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=1831338) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=1831338) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: INFO dbcounter [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] Registered counter for database cinder
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: DEBUG oslo_db.sqlalchemy.engines [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1831338) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: DEBUG dbcounter [-] [1831338] Writer thread running {{(pid=1831338) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: INFO cinder.rpc [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: INFO cinder.rpc [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: DEBUG oslo_db.sqlalchemy.engines [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1831338) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: INFO cinder.volume.manager [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] Determined volume DB was not empty at startup.
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: DEBUG cinder.volume.manager [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] Cinder Volume DB check: vol_db_empty=False {{(pid=1831338) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: WARNING stevedore.named [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: WARNING castellan.key_manager [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: WARNING cinder.keymgr.conf_key_mgr [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume     __import__(mod_str)
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume 
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: ERROR cinder.cmd.volume [None req-d01156f8-8d99-43f5-afb3-3d4742a3ad5e None None] No volume service(s) started successfully, terminating.
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]:   from cryptography.utils import int_from_bytes
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]:   from cryptography.utils import int_from_bytes
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]:   last_heartbeat = column_property(
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]:   num_hosts = column_property(
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jun 25 03:14:50 datacore-PowerEdge-R740 cinder-volume[1831338]:   num_down_hosts = column_property(
Jun 25 03:14:51 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jun 25 03:14:51 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
