-- Logs begin at Wed 2022-07-13 02:54:12 IST, end at Wed 2022-07-13 02:55:26 IST. --
Jul 13 02:54:24 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 13 02:54:26 datacore-PowerEdge-R740 cinder-volume[3487758]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=3487758) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 13 02:54:26 datacore-PowerEdge-R740 cinder-volume[3487758]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=3487758) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: INFO dbcounter [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] Registered counter for database cinder
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: DEBUG oslo_db.sqlalchemy.engines [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3487758) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: DEBUG dbcounter [-] [3487758] Writer thread running {{(pid=3487758) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: INFO cinder.rpc [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: INFO cinder.rpc [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: DEBUG oslo_db.sqlalchemy.engines [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3487758) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: INFO cinder.volume.manager [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] Determined volume DB was empty at startup.
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: DEBUG cinder.volume.manager [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] Cinder Volume DB check: vol_db_empty=True {{(pid=3487758) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: WARNING stevedore.named [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: WARNING castellan.key_manager [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: WARNING cinder.keymgr.conf_key_mgr [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 417, in create
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 158, in __init__
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume 
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: ERROR cinder.cmd.volume [None req-9c296ca6-2f63-43be-b6de-1c40cca83b6e None None] No volume service(s) started successfully, terminating.
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]:   from cryptography.utils import int_from_bytes
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]:   from cryptography.utils import int_from_bytes
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]:   last_heartbeat = column_property(
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]:   num_hosts = column_property(
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 13 02:54:27 datacore-PowerEdge-R740 cinder-volume[3487758]:   num_down_hosts = column_property(
Jul 13 02:54:27 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 13 02:54:27 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
